# Generated by Django 3.1.5 on 2021-06-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_books_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=20, verbose_name='Автору'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(verbose_name='Китепти сүрөттө'),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(max_length=20, verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Китептин баасы'),
        ),
        migrations.AlterField(
            model_name='books',
            name='subtitle',
            field=models.CharField(max_length=100, verbose_name='Кыскача аныктама'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Китептин аты'),
        ),
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.CharField(max_length=100, verbose_name='Чыккан жылы'),
        ),
    ]
